### ISSUE TITLE
Range of the ADI

### ISSUE THREAD

**Issue by kbr3** [NikKrieger/sociome#16]
Hi!

First, I want to thank you so much for your contribution of the sociome package. I needed ADI data at the county level for all of Georgia, and that was unavailable to download from Amy Kind's group at the University of Wisconsin.

However, I noticed that most places (including the UW page) state that the ADI should range from 0 to 100. But I noticed that values from the get_adi function have a mean of 100 and range from 20 to 200-ish. I'm wondering why this is and if there is any documentation on this. We are trying to write it up for a manuscript but want to make sure it is correct first.

Thanks so much for your help!

**Comment by NikKrieger** [comment]
There is actually no hard upper or lower limit to the *localized* ADI values that `sociome::get_adi()` returns. They are created by performing principal components analysis (PCA) with `psych::principal()`, and then the resulting loadings are standardized so that they have a mean of 100 and a standard deviation of 20 (to do this, the loadings are simply multiplied by 20 and then 100 is added). See [Singh 2003](https://doi.org/10.2105/AJPH.93.7.1137) for information on the original calculation of ADI.

Therefore, it is entirely possible (as you have seen) for `get_adi()` to yield ADI values over 200 or even to be negative. For instance, if you see a Georgia county with an ADI of 220, this area's level of deprivation is six standard deviations above the mean level of deprivation of all Georgia counties (which is always 100). This is just (220 - 100) / 20 = 6

An ADI of 0 means that the area's level of deprivation is five standard deviations below the mean level of deprivation of all the areas you chose in your call to `get_adi()`: (0 - 100) / 20 = -5

Indeed, keep in mind that because ADI calculation uses PCA, the ADI values you receive from a single call to `get_adi()` **are only comparable to each other.** If you want to compare Georgia counties to, say, Massachusetts counties, make sure to use `get_adi("county", state = c("GA", "MA"), year = ####, etc.)`, rather than running `get_adi()` separately for each state. If you run the command separately for each state, an ADI of 100 in the Georgia dataset represents the mean deprivation among Georgia counties, whereas an ADI of 100 in the Massachusetts dataset represents the mean deprivation among Massachusetts counties. The mean level of deprivation in Georgia is probably not the same as the mean for Massachusetts.

Let me know if you have any other questions.
