### ISSUE TITLE
Possible to make extraction and calculation of the indicators more flexible? 

### ISSUE THREAD

**Issue by alinefolle** [NikKrieger/sociome#9]
Hi, 

I would like to ask if it would be possible to make more flexible the extraction and calculation of the indicators that compose the ADI. 

Specifically, these are the indicators I'd like to change for my application:

1- I'm using ACS 2005-2009 data and in the code for function calculate_adi( ), in factors_from_acs( ), for the indicator:
                sumprofs        = .data$C24010_003 + .data$C24010_039,

It seems like the correct variable to pull for Females in Management occupations would be C24010_040 instead of C24010_039, which in ACS 2005-2009 corresponds to the Total Females.

2- I'd like to update the income limits for the IncomeDisparity indicator, to be reflective of the year 2000, i.e., using 15K and 75K instead of 10K and 50K. 

I was able to identify and make some changes to the code of get_adi( ) and calculate_adi( ): in make_tidycensus_calls( ) and choose_acs_variables( ), providing a modified dataset to replace acs_vars, and in factors_from_acs( ), changing the code of the indicators calculation, but I was not able to make it run and get a correct call to tidycensus. I'm new to R and this community, so please let me know if you need more information. 

thank you so much!

**Comment by NikKrieger** [comment]
So sorry for not noticing this issue. My email preferences were not properly set. I'll read your message and give you a proper response.

**Comment by NikKrieger** [comment]
Regarding your first request, that's something I definitely do need to fix. I didn't realize that 2009's variable names were different. It's frustrating because I'm going to have to double check all the variables to see if there were any other changes, but thanks for pointing it out.

Regarding the customization of the definitions of the ADI indicators, I'm going to have to ask @atperzynski and @jarrod-dalton if our team is interested in pursuing this.

**Comment by atperzynski** [comment]
Thanks for filing this issue.  In general, I agree with the need to change the income threshold for the income disparity indicator.  Some additional consideration will need to be given to whether $75k is the proper threshold, and for what period, and what to do for more recent years where even $75k might be too low.   There are also some important concerns about how to handle this in circumstances where someone is seeking to look at ADI values across longer periods of time.  I expect that we could include an option like this in a future release. 

I suspect the absolute soonest we make any changes like this would be end of August. 

It's also possible to distill the sociome package down the underlying markdown and you can just edit the code to extract the specific pieces you want. 

Another approach would be for us to incorporate some sort of currency adjustment, centered around the value of currency in a specific year.

**Comment by jarrod-dalton** [comment]
I think we need to discuss how we in general balance between implementing
scientifically-rigorous datasets/models (e.g., published in peer reviewed
journals) vs. supporting users for their wants & needs.

This is a slippery slope that will get even more slippery in proportion to
increasing user counts.

**Comment by NikKrieger** [comment]
A sort of middle-ground approach could be requiring the use of the ~~17~~ 15 ADI indicators, but the user could create custom definitions for one or more of the indicators. That way, it's still Singh / Kind's ADI in some sense. So the `calculate_adi()` function could be defined as follows:
```
calculate_adi <- function(data_raw,
                          keep_indicators = FALSE,
                          seed = NULL,
                          ...,
                          medianFamilyIncome = NULL,
                          medianMortgage = NULL,
                          medianRent = NULL,
                          medianHouseValue = NULL,
                          pctFamiliesInPoverty = NULL,
                          pctOwnerOccupiedHousing = NULL,
                          ratioThoseMakingUnder10kToThoseMakingOver50k = NULL,
                          pctPeopleLivingBelow150PctFederalPovertyLevel = NULL,
                          pctHouseholdsWithChildrenThatAreSingleParent = NULL,
                          pctHouseholdsWithNoVehicle = NULL,
                          pctPeopleWithWhiteCollarJobs = NULL,
                          pctPeopleUnemployed = NULL,
                          pctPeopleWithAtLeastHSEducation = NULL,
                          pctPeopleWithLessThan9thGradeEducation = NULL,
                          pctHouseholdsWithOverOnePersonPerRoom = NULL) {
  # [function definition]
}
```
The function would do what it currently does if the user leaves all the indicators as `NULL`, but the user could specify a different calculation scheme as desired. So in @alinefolle's case, they could do this in order to customize the income threshold:
```
calculate_adi(
  user_data,
  ratioThoseMakingUnder10kToThoseMakingOver50k =
    log(100 * ((B19001_002 + B19001_003) / (B19001_013 + B19001_014 + B19001_015 +B19001_016 + B19001_017)))
)
```

One could argue that this would be helpful especially to people researching area deprivation of non-US locations that don't have US census data. Researchers could plug other data into these indicators.

**Comment by NikKrieger** [comment]
We seem to be sticking with the way indicators are calculated.
